apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-storage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/UnrealQuester/talos-homelab.git
    path: storage
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: local-path-storage
  syncPolicy:
    syncOptions:
      - CreateNamespace=true