---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: victoria-logs
  namespace: logging
spec:
  parentRefs:
  - name: homelab
    namespace: nginx-gateway
    group: gateway.networking.k8s.io	
    kind: Gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /victorialogs
    backendRefs:
    - name: victoria-logs-victoria-logs-single-server
      port: 9428
      group: ''	
      kind: Service
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /select/vmui