server:
  retentionPeriod: 7d
  # -- Data retention max capacity. Default unit is GiB. See these [docs](https://docs.victoriametrics.com/victorialogs/#retention-by-disk-space-usage)
  # retentionDiskSpaceUsage: ""

  persistentVolume:
    size: 20Gi

  extraArgs:
    envflag.enable: true
    envflag.prefix: VM_
    loggerFormat: json
    httpListenAddr: :9428
    http.shutdownDelay: 15s
    syslog.listenAddr.tcp: :514

vector:
  enabled: true