# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/prometheus-operator/kube-prometheus
patches:
- patch: |-
    apiVersion: v1
    kind: Namespace
    metadata:
      name: monitoring
      labels:
        pod-security.kubernetes.io/enforce: privileged