# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/prometheus-operator/kube-prometheus
- grafana-pvc.yaml
- httproute.yaml
patches:
- patch: |-
    apiVersion: v1
    kind: Namespace
    metadata:
      name: monitoring
      labels:
        pod-security.kubernetes.io/enforce: privileged
- patch: |-
    apiVersion: monitoring.coreos.com/v1
    kind: Prometheus
    metadata:
      name: k8s
      namespace: monitoring
    spec:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: local-path
            resources:
              requests:
                storage: 40Gi
      replicas: 1
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: grafana
      namespace: monitoring
    spec:
      template:
        spec:
          volumes:
          - name: grafana-storage
            persistentVolumeClaim:
              claimName: grafana-storage
            emptyDir: null
- patch: |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: grafana-config
      namespace: monitoring
    stringData:
      grafana.ini: |
        [server]
        root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana
        serve_from_sub_path = true
        enable_gzip = true
        [date_formats]
        default_timezone = browser
        user_browser_locale = true