# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v3.1.5/manifests/install.yaml
- app.yaml
patches:
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: argocd-cmd-params-cm
      labels:
        app.kubernetes.io/name: argocd-cmd-params-cm
        app.kubernetes.io/part-of: argocd
    data:
      ## Server properties
      # Value for base href in index.html. Used if Argo CD is running behind reverse proxy under subpath different from / (default "/")
      server.basehref: "/argocd"
      # Used if Argo CD is running behind reverse proxy under subpath different from /
      server.rootpath: "/argocd"
      server.insecure: "true"