apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  parentRefs:
  - name: nginx-gateway
    namespace: nginx-gateway
    group: gateway.networking.k8s.io	
    kind: Gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /argocd
    backendRefs:
    - name: argocd-server
      port: 443
      group: ''	
      kind: Service