# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/nginx/nginx-gateway-fabric/config/crd/gateway-api/experimental?ref=v2.1.1
- https://raw.githubusercontent.com/nginx/nginx-gateway-fabric/v2.1.1/deploy/crds.yaml
- https://raw.githubusercontent.com/nginx/nginx-gateway-fabric/v2.1.1/deploy/default/deploy.yaml
- https://raw.githubusercontent.com/metallb/metallb/v0.15.2/config/manifests/metallb-native.yaml
- addresspool.yaml
- gateway.yaml
- httproute.yaml
patches:
- patch: |-
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: nginx-gateway-cert-generator
      namespace: nginx-gateway
      annotations:
        argocd.argoproj.io/hook: PostSync
        argocd.argoproj.io/hook-delete-policy: HookSucceeded