---
apiVersion: v1
kind: Namespace
metadata:
  name: mariadb-operator
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  replicas: 3
  galera:
    enabled: true
    config:
      reuseStorageVolume: true
  storage:
    size: 2Gi
  service:
    type: LoadBalancer
    metadata:
      annotations:
        metallb.io/allow-shared-ip: "homelab-pool"
    loadBalancerIP: 192.168.0.169
  updateStrategy:
    autoUpdateDataPlane: true
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: test
spec:
  mariaDbRef:
    name: mariadb
  characterSet: utf8
  collate: utf8_general_ci
  cleanupPolicy: Delete
  requeueInterval: 10h
  retryInterval: 30s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: mike
spec:
  mariaDbRef:
    name: mariadb
  passwordSecretKeyRef:
    name: mike
    key: password
  maxUserConnections: 100
  host: "%"
  cleanupPolicy: Delete
  requeueInterval: 10h
  retryInterval: 30s
---
apiVersion: v1
kind: Secret
metadata:
  name: mike
type: Opaque
data:
  # s3cre3t!
  password: czNjcmUzdCE=
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: mike
spec:
  mariaDbRef:
    name: mariadb
  privileges:
  - "ALL PRIVILEGES"
  database: "test"
  table: "*"
  username: mike
  grantOption: true
  host: "%"
  cleanupPolicy: Delete
  requeueInterval: 10h
  retryInterval: 30s
