# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/blake/external-mdns/manifests/rbac
namespace: kube-system
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: external-mdns
    spec:
      template:
        spec:
          containers:
            - name: external-mdns
              args:
                - -source=service
                - -namespace=ingress-nginx
                - -without-namespace=true