# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: vault
    repo: https://helm.releases.hashicorp.com/
    version: 0.31.0
    releaseName: vault
    namespace: vault
    valuesFile: vault-values.yaml
resources:
- namespace.yaml